const nidData = {
    requestId: "3cea572a-c220-4258-a30c-59a8861c5428",
    name: "নোমান ইবনে মিমদাদ",
    nameEn: "Noman Ibne Mimdad",
    gender: "male",
    bloodGroup: "B+",
    dateOfBirth: "1993-11-25",
    father: "মোহাঃ মিমদাদুল ইসলাম",
    mother: "মোসাঃ নুরজাহান বেগম",
    spouse: "",
    nid10Digit: "2810518767",
    occupation: "ছাত্র/ছাত্রী",
    permanentAddress: {
      division: "রাজশাহী",
      district: "চাঁপাইনবাবগঞ্জ",
      rmo: "পল্লী",
      upozila: "শিবগঞ্জ",
      postOffice: "মনাকষা",
      postalCode: "৬৩৪২",
      wardForUnionPorishod: 2,
      additionalMouzaOrMoholla: "",
      additionalVillageOrRoad: "নামোটোলা বিশ্বাসপাড়া",
      homeOrHoldingNo: "-",
      region: "রাজশাহী",
      mouzaOrMoholla: "রাজনগর",
      unionOrWard: "মনাকষা",
      rmoCode: "1"
    },
    photo:"base64Photo",
    presentAddress: {
      division: "রংপুর",
      district: "রংপুর",
      rmoCode: "2",
      rmo: "পৌরসভা",
      upozila: "পীরগঞ্জ",
      cityCorporationOrMunicipality: "পীরগঞ্জ পৌরসভা",
      unionOrWard: "ওয়ার্ড নং-০২",
      postOffice: "পীরগঞ্জ",
      postalCode: "৫৪৭০",
      wardForUnionPorishod: 0,
      additionalMouzaOrMoholla: "",
      additionalVillageOrRoad: "",
      homeOrHoldingNo: "-",
      mouzaOrMoholla: "প্রজা পাড়া",
      villageOrRoad: "প্রজা পাড়া",
      region: "রংপুর"
    },
    nid17Digit: "19937018853000106",
    nid13Digit: "7018853000106",
    homeOrHoldingNo: "-",
    region: "রাজশাহী",
    mouzaOrMoholla: "রাজনগর"
  };

  module.exports.nidData = nidData;